FROM node:16
WORKDIR /app
COPY ./public ./
COPY ./src ./ 
COPY ./index.html ./
COPY ./package.json ./
COPY ./tsconfig.app.json ./
COPY ./tsconfig.json ./
COPY ./tsconfig.node.json ./
RUN npm i
EXPOSE 3002
CMD ["npm","run"]